server:
  port: 8081

spring:
  datasource:
    #jndi-name: jdbc/Sisrev
    #    jndi-name: jdbc/SISREV-DS
    #    jndi-name: jdbc/mantenimiento-ds
    url: jdbc:oracle:thin:@//10.86.1.44:1521/PMMDEV
    #    username: SEGEXT
    #    password: segextdesa
    username: SWLI
    password: 22SD#nITgr#p22mM
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
#      connection-timeout: 20000
      minimum-Idle: 2
      maximun-pool-size: 10
      validation-timeout: 1500000
      max-lifetime: 1500000

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: created
        database-platform: org.hibernate.dialect.Oracle10gDialect
        use-new-id-generator-mappings: false
application:
  url-session: https://dev-logisticainversa.solucionesfps.pe/users/signin
  name: fps-expc-ms-com.farmaciasperuanas.pmmli.materialinformation-materialinformation
  url-material: https://dev-logisticainversa.solucionesfps.pe/master_table/load_master_material
  url_material_lot: https://dev-logisticainversa.solucionesfps.pe/master_table/load_master_material_lot
  url-barcode: https://dev-logisticainversa.solucionesfps.pe/master_table/load_master_barcode
  url_volumetric_data: https://dev-logisticainversa.solucionesfps.pe/master_table/load_master_volumetric_data
  username: serviciosweb
  password: Brainbox2021