server:
  port: 8084
security:
  jwt:
    token:
      secret-key: secret-key.
      expire-length: 864000000
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: notifier.brainbox@gmail.com
    password: Brainbox.2022
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    #jndi-name: jdbc/Sisrev
    #    jndi-name: jdbc/SISREV-DS
    #    jndi-name: jdbc/mantenimiento-ds
    url: jdbc:oracle:thin:@//10.86.1.44/PMMDEV
    #    username: SEGEXT
    #    password: segextdesa
    username: SWLI
    password: 22SD#nITgr#p22mM
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
#      connection-timeout: 20000
      minimum-Idle: 2
      maximun-pool-size: 10
      validation-timeout: 1500000
      max-lifetime: 1500000
    jpa:
      hibernate:
        ddl-auto: created
        database-platform: org.hibernate.dialect.Oracle10gDialect
        use-new-id-generator-mappings: false

    application:
      name: fps-expc-ms-com.farmaciasperuanas.pmmli.monitor-monitor