apiVersion: v1
kind: Service
metadata:
  labels:
    app: fps-expc-ms-com.farmaciasperuanas.pmmli.monitor-monitor
  name: fps-expc-ms-com.farmaciasperuanas.pmmli.monitor-monitor
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 8084
  selector:
    app: fps-expc-ms-com.farmaciasperuanas.pmmli.monitor-monitor
status:
  loadBalancer: {}
